{% set name = "py-wake" %}
{% set version = "2.6.7" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 615f45e347b2d846a014dce0c700bb891538cc7ccff73feee9ddda15da7ba64c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pypandoc
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - xarray
    - netcdf4
    - h5netcdf
    - autograd
    - pyyaml
    - scipy
    - tqdm

test:
  imports:
    - py_wake
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  summary: PyWake a collection of wake models
  dev_url: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simutisernestas
    - madsmpedersen
    - neda-dtu
    - mifm
