{% set name = "py-wake" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py_wake-{{ version }}.tar.gz
  sha256: 72c3cb4d9c87de111d683b36d059690970385384c512d2b4cbfa14ce2b7773b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pypandoc
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - xarray
    - netcdf4
    - h5netcdf
    - autograd
    - pyyaml
    - scipy
    - tqdm

test:
  imports:
    - py_wake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  summary: PyWake a collection of wake models
  dev_url: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simutisernestas
    - madsmpedersen
    - neda-dtu
    - mifm
