{% set name = "py-wake" %}
{% set version = "2.6.9" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/{{ name[0] }}/{{ name }}/py_wake-{{ version }}-py3-none-any.whl
  sha256: 8dea7e1d08e330b640132c43e77007220e01fa0d89653d140eeef89250d3e82c

build:
  noarch: python
  script: | 
    {{ CONDA }} install --yes git-lfs
    {{ PYTHON }} -m pip install -vv py_wake-{{ version }}-py3-none-any.whl
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pypandoc
    - pip
    - setuptools
    - git-lfs
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - xarray >=2024,<2025
    - netcdf4
    - h5netcdf
    - autograd
    - pyyaml
    - scipy
    - tqdm
    - joblib >=1.3
    - git-lfs

test:
  imports:
    - py_wake
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  summary: PyWake a collection of wake models
  dev_url: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  license: MIT
  license_file: py_wake-{{ version }}.dist-info/LICENSE

extra:
  recipe-maintainers:
    - simutisernestas
    - madsmpedersen
    - neda-dtu
    - mifm
