{% set name = "py-wake" %}
{% set version = "2.6.12" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/{{ name[0] }}/{{ name }}/py_wake-{{ version }}-py3-none-any.whl
  sha256: a27ccdf169f14410476178bfc309c8e0259b854cff24eed6d7d218457899e781

build:
  noarch: python
  script: {{ PYTHON }} -m pip install -vv py_wake-{{ version }}-py3-none-any.whl
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pypandoc
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - xarray
    - netcdf4
    - h5netcdf
    - autograd
    - pyyaml
    - scipy
    - tqdm
    - joblib >=1.3
    - git-lfs

test:
  imports:
    - py_wake
  # commands: # git-lfs is not available from conda...
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}
    - git-lfs

about:
  home: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  summary: PyWake a collection of wake models
  dev_url: https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake
  license: MIT
  license_file: py_wake-{{ version }}.dist-info/licenses/LICENSE

extra:
  recipe-maintainers:
    - simutisernestas
    - madsmpedersen
    - neda-dtu
    - mifm
